apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  labels:
    app: home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      initContainers:
      - name: fetchdata
        image: alpine/git:2.40.1
        volumeMounts:
          - name: corrology-home-html-volume
            mountPath: /tmp
          - name: corrology-home-hugo-volume
            mountPath: /www
        command:
        - sh
        - -c
        - git clone --branch main --single-branch https://github.com/corrology/home.git /tmp && /tmp/deploy/build.sh
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: corrology-home-html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: corrology-home-html-volume
        emptyDir: {}
      - name: corrology-home-hugo-volume
        emptyDir: {}
  
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
spec:
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ingress
  namespace: corrology-home
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production-corrology
spec:
  rules:
  - host: dev.corrology.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: home-service
            port:
              number: 80
  - host: www.dev.corrology.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: home-service
            port:
              number: 80
  tls:
  - hosts: 
    - dev.corrology.com
    - www.dev.corrology.com
    secretName: home-dev-corrology-tls-production              